version: '3'

services:
   tidyverse-rjava:
     image: grrrck/tidyverse-rjava:latest
     build:
       context: .
     container_name: tidyverse-rjava
     volumes: 
       - ./import:/home/rstudio/import
     ports:
       - "8787:8787"
     environment:
       USER: SpongeBob
       ROOT: "TRUE"
       PASSWORD: SquarePants
     restart: always

